name: release

on:
  pull_request:
    paths:
      - ".github/workflows/release.yml"
      - ".goreleaser.yaml"
      - "CMakeLists.txt"
      - "flake.lock"
      - "flake.nix"
      - "Makefile"
      - "cmd/**"
      - "go.*"
      - "internal/**"
      - "tuitest/**"
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check GoReleaser config
        run: nix develop --impure --command goreleaser check

      - name: Build snapshot
        if: github.event_name != 'push'
        run: nix develop --impure --command goreleaser release --snapshot --clean --skip=publish

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        run: nix develop --impure --command goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
